# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class MacosDefaults < Formula
  desc "Tool for managing macos defaults declaratively via yaml files"
  homepage "https://github.com/dsully/macos-defaults"
  url "https://github.com/dsully/macos-defaults/archive/v0.0.1.tar.gz"
  sha256 "0614c521d8a8b08173c03302cccec5e336f2038a17d91fd3c8fb4c8d8ba869cf"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dsully/macos-defaults/releases/download/v0.0.1/macos-defaults-0.0.1-darwin-amd64.tar.gz"
      sha256 "bdd9d788efe8f309af720f9feaa20856371d41ab566bb1b0a95d66a8e6a300b0"
    end

    on_arm do
      url "https://github.com/dsully/macos-defaults/releases/download/v0.0.1/macos-defaults-0.0.1-darwin-arm64.tar.gz"
      sha256 "9a651690c343868ab6dc804af2eaa1d3fc47f002d3cd3b7fd0d412448944cf39"
    end
  end

  def install
    bin.install "macos-defaults"

output = Utils.popen_read("#{bin}/macos-saves completions bash")
(bash_completion/"macos-defaults").write output

output = Utils.popen_read("#{bin}/macos-saves completions fish")
(fish_completion/"macos-defaults").write output

output = Utils.popen_read("#{bin}/macos-saves completions zsh")
(zsh_completion/"macos-defaults").write output

prefix.install_metafiles
  end

  test do
    system "macos-defaults -h"
  end
end
