# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class RedditSaves < Formula
  desc "Tool to export reddit saved posts"
  homepage "https://github.com/dsully/reddit-saves"
  url "https://github.com/dsully/reddit-saves/archive/v0.0.2.tar.gz"
  sha256 "99d24d3faf49f543488d38ee5ac4eef6498d4f9e53239aa5f15f5d09c2ab1b9e"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "reddit-saves"
  end

  test do
    system "reddit-saves -h"
  end
end
