# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class RedditSaves < Formula
  desc "Tool to export reddit saved posts"
  homepage "https://github.com/dsully/reddit-saves"
  url "https://github.com/dsully/reddit-saves/archive/v0.0.1.tar.gz"
  sha256 "5c18e3d29d80a424222c4818e1d891772d3422cac916facb873ab3649e115cef"
  license "MIT"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "reddit-saves"
  end

  test do
    reddit-saves -h
  end
end
